package model;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Dec 11 20:53:37 CET 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for Stvari.
     * @return Stvari
     */
    public ViewObjectImpl getStvari() {
        return (ViewObjectImpl) findViewObject("Stvari");
    }

    /**
     * Container's getter for Tipovi1.
     * @return Tipovi1
     */
    public ViewObjectImpl getTipovi1() {
        return (ViewObjectImpl) findViewObject("Tipovi1");
    }

    /**
     * Container's getter for TipoviStvariVL.
     * @return TipoviStvariVL
     */
    public ViewLinkImpl getTipoviStvariVL() {
        return (ViewLinkImpl) findViewLink("TipoviStvariVL");
    }

    /**
     * Container's getter for Tipovi2.
     * @return Tipovi2
     */
    public ViewObjectImpl getTipovi2() {
        return (ViewObjectImpl) findViewObject("Tipovi2");
    }

    /**
     * Container's getter for Stvari1.
     * @return Stvari1
     */
    public ViewObjectImpl getStvari1() {
        return (ViewObjectImpl) findViewObject("Stvari1");
    }

    /**
     * Container's getter for StvariTipoviVL.
     * @return StvariTipoviVL
     */
    public ViewLinkImpl getStvariTipoviVL() {
        return (ViewLinkImpl) findViewLink("StvariTipoviVL");
    }

    /**
     * Container's getter for Stvari2.
     * @return Stvari2
     */
    public ViewObjectImpl getStvari2() {
        return (ViewObjectImpl) findViewObject("Stvari2");
    }
}

